---
version: '3'
services:
  postgresql:
    image: postgres:13
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - 6379
volumes:
  postgresql_data:
